export const categories = [
  {
    id: 1,
    image: "https://i.ibb.co/cXvChqx/fiction.webp",
    title: "Fiction Books",
    link: "/books-fiction",
  },
  {
    id: 2,
    image: "https://i.ibb.co/5YkJRH7/non-Fiction.webp",
    title: "Non Fiction Books",
    link: "/books-nonfiction",
  },
  {
    id: 3,
    image: "https://i.ibb.co/tMf5k48/childrens-Books.webp",
    title: "Children's Books",
    link: "/books-childrens",
  },
];

export const products = [
  {
    id: 1,
    image: "https://i.ibb.co/qnxfpJx/lotr.jpg",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    author: "J. R. R. Tolkien",
    price: 14,
    pages: 432,
    binding: "Hardback/Paperback",
    published: "18.08.2012",
    summary: "Special unjacketed hardback edition of the first part of J.R.R. Tolkien's epic masterpiece, The Lord of the Rings. This edition features the complete story with a unique cover design embellished with gold foil and the iconic maps of Middle-earth appearing in red and black as endpapers. Sauron, the Dark Lord, has gathered to him all the Rings of Power - the means by which he intends to rule Middle-earth. All he lacks in his plans for dominion is the One Ring - the ring that rules them all - which has fallen into the hands of the hobbit, Bilbo Baggins. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.",
    extra: "Best Selling Books",
  },
  {
    id: 2,
    image: "https://i.ibb.co/D5JbFS5/witcher.jpg",
    title: "The Witcher: The Last Wish",
    author: "Andrzej Sapkowski",
    price: 20,
    extra: "Best Selling Books",
  },
  {
    id: 3,
    image: "https://i.ibb.co/xf7SxNw/got.jpg",
    title: "A Game of Thrones",
    author: "George R. R. Martin",
    price: 15,
    extra: "Best Selling Books",
  },
  {
    id: 4,
    image: "https://i.ibb.co/LCfC9g2/babel.jpg",
    title: "Babel: An Arcane History",
    author: "R.F. Kuang",
    price: 16,
    extra: "Best Selling Books",
  },
  {
    id: 5,
    image: "https://i.ibb.co/cTCK1tc/tudor.jpg",
    title: "House of Tudor: A Grisly History",
    author: "Mickey Mayhew",
    price: 10,
    extra: "Best Selling Books",
  },
  {
    id: 6,
    image: "https://i.ibb.co/dW6T011/phillars.jpg",
    title: "The Pillars of the Earth",
    author: "Ken Follett",
    price: 12,
    extra: "Best Selling Books",
  },
  {
    id: 7,
    image: "https://i.ibb.co/Z1HNZ5W/court.jpg",
    title: "A Court of Mist and Fury",
    author: "Sarah J. Maas",
    price: 10,
    extra: "Best Selling Books",
  },
  {
    id: 8,
    image: "https://i.ibb.co/nDWMHH6/harry.jpg",
    title: "Harry Potter and the Philosopher’s Stone",
    author: "J. K. Rowling",
    price: 23,
    extra: "Best Selling Books",
  },
  {
    id: 9,
    image: "https://i.ibb.co/Tmtbzxt/history.jpg",
    title: "The Times Complete History of the World",
    author: "Richard Overy",
    price: 6,
    extra: "Best Selling Books",
  },
  {
    id: 10,
    image: "https://i.ibb.co/RP5ZryF/9781472157362.jpg",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    price: 10,
    extra: "Best Selling Books",
  },
  {
    id: 11,
    image: "https://i.ibb.co/M2J2cDH/9781510105263-04124cdb-8f13-46e0-a591-c5215d34a77e.jpg",
    title: "Siege and Storm: Book 2 (Shadow and Bone)",
    author: "Leigh Bardugo",
    price: 9,
    extra: "What Everyone's Talking About",
  },
  {
    id: 12,
    image: "https://i.ibb.co/LNvfm2W/9780241377093.jpg",
    title: "The Dark is Rising",
    author: "Susan Cooper",
    price: 9,
    extra: "What Everyone's Talking About",
  },
  {
    id: 13,
    image: "https://i.ibb.co/2WRbBG9/peoplehacker.jpg",
    title: "People Hacker",
    author: "Jenny Radcliffe",
    price: 14,
    extra: "What Everyone's Talking About",
  },
  {
    id: 14,
    image: "https://i.ibb.co/7yMkn4n/9780712354073.jpg",
    title: "Final Acts: Theatrical Mysteries",
    author: "Martin Edwards",
    price: 10,
    extra: "What Everyone's Talking About",
  },
  {
    id: 15,
    image: "https://i.ibb.co/JzwjsVV/9780367568948-fa14c0b5-38fd-4b1d-bb7b-a29a0c3e186e.jpg",
    title: "Icons of Sound: Voice, Architecture, and Imagination in Medieval Art",
    author: "Bissera V. Pentcheva",
    price: 10,
    extra: "What Everyone's Talking About",
  },
];