export const categories = [
  {
    id: 1,
    image: "https://i.ibb.co/cXvChqx/fiction.webp",
    title: "Fiction Books",
    link: "/books-fiction",
  },
  {
    id: 2,
    image: "https://i.ibb.co/5YkJRH7/non-Fiction.webp",
    title: "Non Fiction Books",
    link: "/books-nonfiction",
  },
  {
    id: 3,
    image: "https://i.ibb.co/tMf5k48/childrens-Books.webp",
    title: "Children's Books",
    link: "/books-childrens",
  },
];

export const products = [
  {
    id: 1,
    image: "https://i.ibb.co/qnxfpJx/lotr.jpg",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    author: "J. R. R. Tolkien",
    price: 14,
    pages: 432,
    genre: "fiction",
    binding: "Hardback",
    published: "18.08.2012",
    summary: "Special unjacketed hardback edition of the first part of J.R.R. Tolkien's epic masterpiece, The Lord of the Rings. This edition features the complete story with a unique cover design embellished with gold foil and the iconic maps of Middle-earth appearing in red and black as endpapers. Sauron, the Dark Lord, has gathered to him all the Rings of Power - the means by which he intends to rule Middle-earth. All he lacks in his plans for dominion is the One Ring - the ring that rules them all - which has fallen into the hands of the hobbit, Bilbo Baggins. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.",
    extra: "Best Selling Books",
  },
  {
    id: 2,
    image: "https://i.ibb.co/D5JbFS5/witcher.jpg",
    title: "The Witcher: The Last Wish",
    author: "Andrzej Sapkowski",
    price: 20,
    pages: 336,
    genre: "fiction",
    binding: "Hardback",
    published: "16.12.2021",
    summary: "Experience the world of the Witcher like never before with this stunning deluxe hardcover edition of The Last Wish! Featuring seven gorgeous illustrations from seven award-winning artists - one for each story in the collection of adventures - it celebrates the first chapter of the bestselling, groundbreaking series that inspired the hit Netflix show and the blockbuster video games. Introducing Geralt the Witcher - revered and hated - who holds the line against the monsters plaguing humanity in the bestselling series that inspired the Witcher video games and a major Netflix show. Geralt of Rivia is a Witcher, a man whose magic powers and lifelong training have made him a brilliant fighter and a merciless assassin. Yet he is no ordinary killer: he hunts the vile fiends that ravage the land and attack the innocent. But not everything monstrous-looking is evil; not everything fair is good . . . and in every fairy tale there is a grain of truth.",
    extra: "Best Selling Books",
  },
  {
    id: 3,
    image: "https://i.ibb.co/xf7SxNw/got.jpg",
    title: "A Game of Thrones",
    author: "George R. R. Martin",
    price: 15,
    pages: 896,
    genre: "fiction",
    binding: "Hardback",
    published: "18.10.2016",
    summary: "Published in celebration of the twentieth anniversary of George R. R. Martin's landmark series, this lavishly illustrated special edition of A Game of Thrones-with gorgeous full-page illustrations in every chapter-revitalizes the fantasy masterpiece that became a cultural phenomenon. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the North of Winterfell, sinister and supernatural forces are massing beyond the kingdom's protective Wall. At the centre of the conflict lie the Starks of Winterfell, a family as harsh and unyielding as the land they were born to. Sweeping from a region of brutal cold to a distant summertime kingdom of epicurean plenty, here is a tale of lords and ladies, soldiers and sorcerers, assassins and bastards, who come together in a time of grim omens. Amid plots and counterplots, tragedy and betrayal, victory and terror, the fate of the Starks, their allies, and their enemies hangs perilously in the balance, as each endeavours to win that deadliest of conflicts: the game of thrones.",
    extra: "Best Selling Books",
  },
  {
    id: 4,
    image: "https://i.ibb.co/LCfC9g2/babel.jpg",
    title: "Babel: An Arcane History",
    author: "R.F. Kuang",
    price: 16,
    pages: 560,
    genre: "fiction",
    binding: "Hardback",
    published: "01.09.2022",
    summary: "Traduttore, traditore: An act of translation is always an act of betrayal. Oxford, 1836. The city of dreaming spires. It is the centre of all knowledge and progress in the world. And at its centre is Babel, the Royal Institute of Translation. The tower from which all the power of the Empire flows. Orphaned in Canton and brought to England by a mysterious guardian, Babel seemed like paradise to Robin Swift. Until it became a prison... But can a student stand against an empire? An incendiary new novel from award-winning author R.F. Kuang about the power of language, the violence of colonialism, and the sacrifices of resistance. 'A masterpiece that resonates with power and knowledge. BABEL is a stark picture of the cruelty of empire, a distillation of dark academia, and a riveting blend of fantasy and historical fiction - a monumental achievement'",
    extra: "Best Selling Books",
  },
  {
    id: 5,
    image: "https://i.ibb.co/cTCK1tc/tudor.jpg",
    title: "House of Tudor: A Grisly History",
    author: "Mickey Mayhew",
    price: 10,
    pages: 200,
    genre: "nonfiction",
    binding: "Paperback",
    published: "18.02.2022",
    summary: "Gruesome but not gratuitous, this decidedly darker take on the Tudors, from 1485 to 1603, covers some forty-five events' from the Tudor reign, taking in everything from the death of Richard III to the botched execution of Mary Queen of Scots, and a whole host of horrors in between. Particular attention is paid to the various gruesome ways in which the Tudors despatched their various villains and lawbreakers, from simple beheadings, to burnings and of course the dreaded hanging, drawing and quartering. Other chapters cover the various diseases prevalent during Tudor times, including the dreaded Sweating Sickness' -rather topical at the moment, unfortunately -as well as the cures for these sicknesses, some of which were considered worse than the actual disease itself. The day-to-day living conditions of the general populace are also examined, as well as various social taboos and the punishments that accompanied them, i.e. the stocks, as well as punishment by exile. Tudor England was not a nice place to live by 21st century standards, but the book will also serve to explain how it was still nevertheless a familiar home to our ancestors.",
    extra: "Best Selling Books",
  },
  {
    id: 6,
    image: "https://i.ibb.co/dW6T011/phillars.jpg",
    title: "The Pillars of the Earth",
    author: "Ken Follett",
    price: 12,
    pages: 1104,
    genre: "fiction",
    binding: "Paperback",
    published: "13.07.2017",
    summary: "The girl turned her hypnotic golden eyes on the three strangers, the knight, the monk and the priest; and then she pronounced her curse, callling out the words in ringing tones: 'I curse you with sickness and sorrow, with hunger and pain; your house shall be consumed by fire and your children shall die in the gallows; your enemies shall prosper, and you shall grow old in sadness and regret...' So begins a spellbinding epic tale of ambition, anarchy, and absolute power set against the sprawling medieval canvas of twelfth-century England, this is Ken Follett's classic historical masterpiece, the first novel in the epic Kingsbridge Series. The Pillars of the Earth is the story of Philip, prior of Kingsbridge, a devout and resourceful monk driven to build the greatest Gothic cathedral the world has known. It is the story of Tom, the mason who becomes his architect - a man divided in his soul who will be divided by love and tortured by duty and divided loyalty. It is the story of the beautiful, resourceful, elusive Lady Aliena, haunted by a secret shame, driven by a bitter determination and destined to shape her own destiny and others... But most of all it is a story of a community shaped by history and of the ultimate struggle between good and evil that will turn church against state, and brother against brother.",
    extra: "Best Selling Books",
  },
  {
    id: 7,
    image: "https://i.ibb.co/Z1HNZ5W/court.jpg",
    title: "A Court of Mist and Fury",
    author: "Sarah J. Maas",
    price: 10,
    pages: 656,
    genre: "fiction",
    binding: "Paperback",
    published: "02.06.2020",
    summary: "Feyre survived Amarantha's clutches to return to the Spring Court - but at a steep cost. Though she now possesses the powers of the High Fae, her heart remains human, and it can't forget the terrible deeds she performed to save Tamlin's people. Nor has Feyre forgotten her bargain with Rhysand, the mesmerising High Lord of the feared Night Court. As Feyre navigates his dark web of political games and tantalising promises, a greater evil looms - and she might be key to stopping it. But only if she can step into her growing power, heal her fractured soul and have the courage to shape her own future - and the future of a world cloven in two...",
    extra: "Best Selling Books",
  },
  {
    id: 8,
    image: "https://i.ibb.co/nDWMHH6/harry.jpg",
    title: "Harry Potter and the Philosopher’s Stone",
    author: "J. K. Rowling",
    price: 23,
    pages: 656,
    genre: "childrens",
    binding: "Hardback",
    published: "20.10.2020",
    summary: "An irresistible new edition of Harry Potter and the Philosopher's Stone created with ultra-talented designers MinaLima, the design magicians behind the gorgeous visual graphic style of the Harry Potter and Fantastic Beasts films. J.K. Rowling's complete and unabridged text is accompanied by MinaLima's handsome colour illustrations on nearly every page, superb design, and eight exclusive interactive paper-engineered elements - including Harry's Hogwarts letter, the magical entrance to Diagon Alley, a sumptuous feast in the Great Hall of Hogwarts and more. Designed and illustrated by the iconic house of MinaLima - best known for establishing the graphic design of the Harry Potter and Fantastic Beasts films - this is the perfect gift for Harry Potter fans and a beautiful addition to any collector's bookshelf, enticing readers of all ages to discover the Harry Potter novels all over again.",
    extra: "Best Selling Books",
  },
  {
    id: 9,
    image: "https://i.ibb.co/Tmtbzxt/history.jpg",
    title: "The Times Complete History of the World",
    author: "Richard Overy",
    price: 16,
    pages: 432,
    genre: "nonfiction",
    binding: "Hardback",
    published: "30.09.2010",
    summary: "The ultimate work of historical reference From cavemen to the Cold War, from Alexander the Great to global warming, from warfare through the ages to the great voyages of exploration, The Times Complete History of the World is the book that has all the answers. This is the most comprehensive, authoritative and accessible work on world history available today. It has sold over 2.25million copies and has been translated into 18 other languages since its first publication in 1978. With a narrative scope covering the origins of mankind right through to the turmoil of the 21st century, this book is an unrivalled and breathtaking accomplishment. With over 600 full-colour maps and charts on a wide range of historical subjects and representing the work of a team of professional historians, this new edition continues a tradition of nearly thirty years of excellence, style, authority and cutting-edge design. This edition is also internet-linked. Readers can follow the weblinks in the book to acess the most up to date information permitting further in-depth exploration of key subjects. With fully up-to-date text, including material on Iraq and Afghanistan, terrorism, Israel and the EU, this book, edited by leading modern historian Professor Richard Overy, is broad-ranging and more visually enticing than ever. Updates for the eighth edition include: - New material on the United States - The most up-to-date research on prehistory - Reworked spreads on the Middle East, including a new spread on Iran - Current information on the global economy, the global environment, warfare and world terrorism - New introduction - Short biographies of 100 key figures in world history.",
    extra: "Best Selling Books",
  },
  {
    id: 10,
    image: "https://i.ibb.co/RP5ZryF/9781472157362.jpg",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    price: 10,
    pages: 384,
    genre: "fiction",
    binding: "Paperback",
    published: "28.06.2022",
    summary: "For years, rumours of the 'Marsh Girl' have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark, the so-called Marsh Girl. But Kya is not what they say. Sensitive and intelligent, she has survived for years alone in the marsh that she calls home, finding friends in the gulls and lessons in the sand. Then the time comes when she yearns to be touched and loved. When two young men from town become intrigued by her wild beauty, Kya opens herself to a new life - until the unthinkable happens.",
    extra: "Best Selling Books",
  },
  {
    id: 11,
    image: "https://i.ibb.co/M2J2cDH/9781510105263-04124cdb-8f13-46e0-a591-c5215d34a77e.jpg",
    title: "Siege and Storm: Book 2 (Shadow and Bone)",
    author: "Leigh Bardugo",
    price: 9,
    pages: 416,
    genre: "childrens",
    binding: "Paperback",
    published: "26.06.2018",
    summary: "Enter the Grishaverse with book two of the Shadow and Bone Trilogy by number one New York Times-bestselling author Leigh Bardugo. Perfect for fans of Laini Taylor and Sarah J. Maas. Now with a stunning new cover and exclusive bonus material: Nikolai Lantsov character art and a Q&A with Leigh Bardugo. Soldier. Summoner. Saint. Alina Starkov's power has grown, but not without a price. She is the Sun Summoner - hunted across the True Sea, haunted by the lives she took on the Shadow Fold. But she and Mal can't outrun their enemies for long. The Darkling is more determined than ever to claim Alina's magic and use it to take the Ravkan throne. With nowhere else to turn, Alina enlists the help of an infamous privateer and sets out to lead the Grisha army. But as the truth of Alina's destiny unfolds, she slips deeper into the Darkling's deadly game of forbidden magic, and further away from her humanity. To save her country, Alina will have to choose between her power and the love she thought would always be her shelter. No victory can come without sacrifice - and only she can face the oncoming storm. Read all the books in the Grishaverse! The Shadow and Bone Trilogy (previously published as The Grisha Trilogy) Shadow and Bone Siege and Storm Ruin and Rising The Six of Crows Duology Six of Crows Crooked Kingdom The Language of Thorns: Midnight Tales and Dangerous Magic",
    extra: "What Everyone's Talking About",
  },
  {
    id: 12,
    image: "https://i.ibb.co/LNvfm2W/9780241377093.jpg",
    title: "The Dark is Rising",
    author: "Susan Cooper",
    price: 9,
    pages: 384,
    genre: "childrens",
    binding: "Paperback",
    published: "14.11.2019",
    summary: "This night will be bad and tomorrow will be beyond imagining. It's Midwinter's Eve, the day before Will's eleventh birthday. But there is an atmosphere of fear in the familiar countryside around him. This will be a birthday like no other. Will discovers that he has the power of the Old Ones, and that he must embark on a quest to vanquish the terrifyingly evil magic of the Dark.",
    extra: "What Everyone's Talking About",
  },
  {
    id: 13,
    image: "https://i.ibb.co/2WRbBG9/peoplehacker.jpg",
    title: "People Hacker",
    author: "Jenny Radcliffe",
    price: 14,
    pages: 304,
    genre: "nonfiction",
    binding: "Hardback",
    published: "16.02.2023",
    summary: "'From an early age, locked doors, high fences and the secrets kept by businesses, buildings and people, fascinated me. I wanted to find out what they wanted to hide away.' A burglar for hire, con-artist and expert in deception and physical infiltration - Jenny Radcliffe is a professional people hacker. After being schooled in the art of breaking and entering by her family, she became an expert social engineer, doing an insider's job to exploit the flaws and weaknesses in top-grade security operations. In People Hacker, Jenny reveals how she uses her inimitable blend of psychology, stagecraft and charm to gain access to top-grade private and commercial properties. From the back streets of Liverpool to the City of London's Square Mile, across rooftops, cellars and staircases in Europe to the mansions of gangsters in the Far East, Jenny has risked it all to earn the title 'People Hacker'. This is Jenny insider's account of how her working-class upbringing, northern sense of humour and femininity in a male-dominated industry all helped her to become one of the most sought-after social engineers in the world. Told in her trademark colourful style, and packed full of stories of the crazy and dangerous situations she has found herself in along the way, Jenny shines a light on the security mistakes we all make - and how to avoid them.",
    extra: "What Everyone's Talking About",
  },
  {
    id: 14,
    image: "https://i.ibb.co/7yMkn4n/9780712354073.jpg",
    title: "Final Acts: Theatrical Mysteries",
    author: "Martin Edwards",
    price: 10,
    pages: 352,
    genre: "fiction",
    binding: "Paperback",
    published: "10.09.2022",
    summary: "Behind the stage lights and word-perfect soliloquies, sinister secrets are lurking in the wings. The mysteries in this collection reveal the dark side to theatre and performing arts: a world of backstage dealings, where unscrupulous actors risk everything to land a starring role, costumed figures lead to mistaken identities, and on-stage deaths begin to look a little too convincing. . . This expertly curated thespian anthology features fourteen stories from giants of the classic crime genre such as Dorothy L. Sayers, Julian Symons and Ngaio Marsh, as well as firm favourites from the British Library Crime Classics series: Anthony Wynne, Christianna Brand, Bernard J. Farmer and many more. Mysteries abound when a player's fate hangs on a single performance, and opening night may very well be their last.",
    extra: "What Everyone's Talking About",
  },
  {
    id: 15,
    image: "https://i.ibb.co/JzwjsVV/9780367568948-fa14c0b5-38fd-4b1d-bb7b-a29a0c3e186e.jpg",
    title: "Icons of Sound: Voice, Architecture, and Imagination in Medieval Art",
    author: "Bissera V. Pentcheva",
    price: 39,
    pages: 280,
    genre: "nonfiction",
    binding: "Paperback",
    published: "30.05.2022",
    summary: "Icons of Sound: Voice, Architecture, and Imagination in Medieval Art brings together art history and sound studies to offer new perspectives on medieval churches and cathedrals as spaces where the perception of the visual is inherently shaped by sound. The chapters encompass a wide geographic and historical range, from the fifth to the fifteenth century, and from Armenia and Byzantium to Venice, Rome, and Santiago de Compostela. Contributors offer nuanced explorations of the intangible sonic aura produced in these places by the ritual music and harness the use of digital technology to reconstruct historical aural environments. Rooted in a decade-long interdisciplinary research project at Stanford University, Icons of Sound expands our understanding of the inherently intertwined relationship between medieval chant and liturgy, the acoustics of architectural spaces, and their visual aesthetics. Together, the contributors provide insights that are relevant across art history, sound studies, musicology, and medieval studies.",
    extra: "What Everyone's Talking About",
  },
];